### ISSUE TITLE
Quotes are not properly escaped

### ISSUE THREAD

**Issue by rgarg8** [twilson63/html2haml#16]
This code:

```
<div class="hello <%= "bye" if @welcome.nil? %>">
</div>
```

Generates:

```
%div{:class => "hello #{"bye" if @welcome.nil?}"}
```

Which will break because the quote is improperly closed.

**Comment by twilson63** [comment]
Hello,

I don't know how I can fix this, any suggestions?

Thanks

Tom

**Comment by emptyflask** [comment]
What's the problem? This works fine, at least with the current version of Haml.
