### ISSUE TITLE
no such file to load -- spec (LoadError)

### ISSUE THREAD

**Issue by ferriswheel** [twilson63/html2haml#2]
hello,

installing html2haml and got this on first try

$ ruby  html2haml_spec.rb 
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- spec (LoadError)
        from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from html2haml_spec.rb:4

the gem env and installed gems follow.

what have i missed or do i need ruby 1.9?

regards 

john

the gem env is

$ gem env 
RubyGems Environment:
- RUBYGEMS VERSION: 1.3.7
- RUBY VERSION: 1.8.7 (2008-08-11 patchlevel 72) [i486-linux]
- INSTALLATION DIRECTORY: /usr/lib/ruby/gems/1.8
- RUBY EXECUTABLE: /usr/bin/ruby1.8
- EXECUTABLE DIRECTORY: /usr/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - x86-linux
- GEM PATHS:
  - /usr/lib/ruby/gems/1.8
  - /home/lawsonst/.gem/ruby/1.8
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :benchmark => false
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - http://rubygems.org/

the installed gems are

$ gem list 

**\* LOCAL GEMS ***

abstract (1.0.0)
action_mailer_tls (1.1.3)
actionmailer (3.0.1, 3.0.0, 2.3.8, 2.3.5, 2.1.1, 2.0.2, 1.3.0)
actionpack (3.0.1, 3.0.0, 2.3.8, 2.3.5, 2.1.1, 2.0.2, 1.13.6, 1.13.0)
actionwebservice (1.2.6, 1.2.0)
activemodel (3.0.1, 3.0.0)
activerecord (3.0.1, 3.0.0, 2.3.8, 2.3.5, 2.1.1, 2.0.2, 1.15.6, 1.15.0)
activeresource (3.0.1, 3.0.0, 2.3.8, 2.3.5, 2.1.1, 2.0.2)
activesupport (3.0.1, 3.0.0, 2.3.8, 2.3.5, 2.1.1, 2.0.2, 1.4.4, 1.4.0)
acts_as_list (0.1.2)
addressable (2.2.2, 2.2.1, 2.2.0, 2.1.1)
arel (2.0.1, 1.0.1)
at-the-movies (0.1.0)
authlogic (2.1.6, 2.1.3)
babosa (0.2.0)
builder (2.1.2)
bundler (1.0.3, 1.0.2, 1.0.0, 0.9.19)
capistrano (2.5.19)
cgi_multipart_eof_fix (2.5.0)
cmdparse (2.0.2)
creole (0.3.7)
daemon_controller (0.2.5)
daemons (1.1.0)
data_objects (0.10.2, 0.10.1)
datamapper (1.0.2)
desert (0.5.4, 0.5.3)
diff-lcs (1.1.2)
dm-aggregates (1.0.2)
dm-constraints (1.0.2)
dm-core (1.0.2)
dm-do-adapter (1.0.2)
dm-migrations (1.0.2)
dm-serializer (1.0.2)
dm-sqlite-adapter (1.0.2)
dm-timestamps (1.0.2)
dm-transactions (1.0.2)
dm-types (1.0.2)
dm-validations (1.0.2)
do_mysql (0.10.2, 0.10.1)
do_sqlite3 (0.10.2, 0.10.1.1)
echoe (4.3.1, 4.3, 4.1)
erubis (2.6.6)
escape_utils (0.1.9)
evaluator (0.1.5)
eventmachine (0.12.10)
exifr (1.0.3, 0.10.9)
extlib (0.9.15)
fastercsv (1.5.3)
fastthread (1.0.7)
ffi (0.6.3, 0.5.4)
file-tail (1.0.5)
friendly_id (3.1.7, 2.3.0)
gem_plugin (0.2.3)
gemcutter (0.6.1, 0.5.0)
gitrb (0.2.7)
grit (2.3.0)
haml (3.0.22, 3.0.21, 2.2.19)
has_scope (0.5.0)
highline (1.6.1)
hoe (2.6.2)
hpricot (0.8.2)
i18n (0.4.1)
inherited_resources (1.1.2, 0.9.5)
json_pure (1.4.6, 1.2.4, 1.2.0)
juicer (1.0.8, 1.0.7, 1.0.3)
kgio (1.3.1)
less (1.2.21)
macaddr (1.0.0)
mail (2.2.7, 2.2.6.1)
maruku (0.6.0)
mechanize (1.0.0)
memcache-client (1.8.5, 1.8.2)
mime-types (1.16)
mimemagic (0.1.7)
mongrel (1.1.5)
mutter (0.5.3)
mysql (2.8.1)
net-scp (1.0.4)
net-sftp (2.0.5)
net-ssh (2.0.23)
net-ssh-gateway (1.0.1)
nokogiri (1.4.3.1, 1.4.1)
org-ruby (0.5.3)
paperclip (2.3.4, 2.3.1.1)
passenger (3.0.0)
Piggy (0.5.0.0)
polyglot (0.3.1)
pony (1.0.1)
rack (1.2.1, 1.1.0, 1.0.1)
rack-mount (0.6.13)
rack-test (0.5.6, 0.5.5)
radiant (0.9.1, 0.8.1)
rails (3.0.1, 3.0.0, 2.3.8, 2.3.5, 2.1.1, 2.0.2, 1.2.0)
railties (3.0.1, 3.0.0)
rake (0.8.7)
rdiscount (1.6.5, 1.5.8)
RedCloth (4.2.3, 4.2.2)
responders (0.6.2)
rspec (2.0.1)
rspec-core (2.0.1)
rspec-expectations (2.0.1)
rspec-mocks (2.0.1)
rubyforge (2.0.4, 2.0.3)
rubygems-update (1.3.7, 1.3.6)
rubypants (0.2.0)
rubyzip (0.9.4)
sequel (3.16.0)
sinatra (1.1.0, 1.0)
slim (0.7.0)
spruz (0.1.5)
sqlite3-ruby (1.3.2, 1.3.1, 1.2.5)
stringex (1.2.0, 1.1.0)
syntax (1.0.0)
temple (0.1.3)
test-spec (0.10.0)
thin (1.2.7)
thor (0.14.3, 0.14.1)
tilt (1.1)
treetop (1.4.8)
tzinfo (0.3.23)
unicode (0.4.0)
unicorn (2.0.0)
utf8proc (1.1.5)
uuid (2.3.1)
uuidtools (2.1.1)
will_paginate (2.3.15, 2.3.12)
yajl-ruby (0.7.8)

**Comment by twilson63** [comment]
I will take a look at it, I need to upgrade the project to use bundler, which should correct these issues.

Thanks
