### ISSUE TITLE
Copyright Symbol Crashes App

### ISSUE THREAD

**Issue by rltrent** [twilson63/html2haml#6]
Use of the copyright symbol (©) anywhere in a page's code causes the application to crash and display an Internal Server Error. Possibly a Heroku issue, non-specific to this app.

**Comment by twilson63** [comment]
Interesting, does your mark up use &copy; ?  Can you provide a sample?

Thanks

**Comment by twilson63** [comment]
Sorry, I don't think my comment was clear,

Does your markup use & copy ; to generate the copy symbol  or the symbol itself?

**Comment by iangreenleaf** [comment]
Looks like any Unicode character will do this. Inputting only `ó` will crash the app. Does not happen on a local checkout, so it seems to be related to Heroku.

**Comment by twilson63** [comment]
Resolved, I just had to enable utf encodings for 1.9.2 - Thanks for reporting this issue.

**Comment by rltrent** [comment]
Thanks :)
