### ISSUE TITLE
Feature: Choose tab-spacing rather than single-spacing

### ISSUE THREAD

**Issue by jvenator** [twilson63/html2haml#7]
As a disclaimer, I am a newbie. This tool/your work has been a huge help to me, so many thanks! And apologies if this is not the right place to put something like this.

When converting various html.erb snippets in to html.haml I have run into rendering issues when there is inconsistent use of single-spaces and tabs. If there was a way to choose which we prefer on the html2haml website that would be amazing. Perhaps similar to the way I can select how spaces a "tab" equates to in TextMate.

**Comment by twilson63** [comment]
If you can provide an example where this is an issue, that would be helpful.

maybe I can just remove all the tabs in the erb before converting and that
would resolve the issue.  Or I can provide the option,
just need to full understand the issue.

Thanks

On Mon, Jul 4, 2011 at 2:27 AM, slipshot <
reply@reply.github.com>wrote:

> As a disclaimer, I am a newbie. This tool/your work has been a huge help to
> me, so many thanks! And apologies if this is not the right place to put
> something like this.
> 
> When converting various html.erb snippets in to html.haml I have run into
> rendering issues when there is inconsistent use of single-spaces and tabs.
> If there was a way to choose which we prefer on the html2haml website that
> would be amazing. Perhaps similar to the way I can select how spaces a "tab"
> equates to in TextMate.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/twilson63/html2haml/issues/7

## 

Tom Wilson
Jack Russell Software Company   LLC
1067 Cliffwood Drive
Mount Pleasant, SC  29464
Phone: 843-606-0637
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar: http://www.jackhq.com/calendar
