### ISSUE TITLE
empty tags

### ISSUE THREAD

**Issue by axaluss** [twilson63/html2haml#9]
empty tags are not converted properly

```
...
<script …>
</script>
</head>
<body>

->

%script
  %body
```

**Comment by twilson63** [comment]
Cool, thanks for the feedback, I will take a look at.

**Comment by twilson63** [comment]
Reproduced...

```
<html>
<head>
<script type='text/javascript'>
</script>
</head>
<body>
</body>
</html>
```

# 

```
%html
  %head
    :javascript
        %body

```

Should Equal

```
%html
  %head
    :javascript
   %body

```

# 

I wonder if it is an empty script tag, should we just strip it out all together?  Why would you have an empty script tag?

**Comment by axaluss** [comment]
it can damage your html output maybe not only during development and slow you down.
are there other tags which dont like to be empty?

**Comment by twilson63** [comment]
My guess it would be the same for the 

```
<style> 
```

tag as well.

**Comment by twilson63** [comment]
Fixed in html2haml gem..

``` html
<script src=''>
</script>
</head>
<body>
```

``` haml
%script{:src => ""}
%body/
```
